title: Bagisto - Documentation
email: support@bagisto.com
description:
  This is official documentation site for Bagisto. Go ahead
  and try one of the most easiest e-commerce frameworks ever.

url: https://devdocs.bagisto.com

baseurl: "/1.1.x"
destination: "_site/1.1.x"

twitter_username: bagistoshop
github_username: bagisto

highlighter: rouge
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
sass_dir: _sass

load_paths:
  - /assets/style/

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
